/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_Prominic_runtime_UnixProcess */

#ifndef _Included_com_Prominic_runtime_UnixProcess
#define _Included_com_Prominic_runtime_UnixProcess
#ifdef __cplusplus
extern "C" {
#endif
#undef com_Prominic_runtime_UnixProcess_MAX_PROCESSES
#define com_Prominic_runtime_UnixProcess_MAX_PROCESSES 64L
/*
 * Class:     com_Prominic_runtime_UnixProcess
 * Method:    exec
 * Signature: (II[Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_Prominic_runtime_UnixProcess_exec
  (JNIEnv *, jobject, jint, jint, jobjectArray, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
